#
# apache
#

apache_document_root: "/var/www/{{ apache_server_name }}"

# vars below are used by predefined role from ansible galaxy

apache_remove_default_vhost: true
apache_vhosts:
  - servername: "{{ apache_server_name }}"
    documentroot: "{{ apache_document_root }}"

apache_mods_enabled:
  - php5.load
  - rewrite.load

#
# mysql
#

ocla_db_user_name: ocla_db_user
ocla_db_user_pass: password
ocla_db_name: oclaca_wp934

# vars below are used by predefined role from ansible galaxy

mysql_port: 3306
mysql_bind_address: "127.0.0.1"
mysql_root_password: ''              # The new root password
mysql_default_root_password: ''      # The root password

mysql_databases:
  - name: "{{ ocla_db_name }}"
    encoding: "utf8"

mysql_users:
  - name: "{{ ocla_db_user_name }}"
    pass: "{{ ocla_db_user_pass }}"
    priv: "*.*:ALL"  # optional, defaults to "*.*:ALL"
    host: "localhost"


#
# wordpress
#

# vars below are used by predefined role from ansible galaxy

wp_version: 4.0
wp_install_dir: "{{ apache_document_root }}"
wp_db_name: "{{ ocla_db_name }}"
wp_db_user: "{{ ocla_db_user_name }}"
wp_db_password: "{{ ocla_db_user_pass }}"
wp_db_host: "localhost"

#
# backup and restore
#

remote_backup_dir: /tmp/ocla.ca_backup
remote_backup_mysql_dump: "{{ remote_backup_dir }}/mysql/oclaca_wp934.sql"
remote_backup_wordpress_dir: "{{ remote_backup_dir }}/wordpress"

remote_backup_archive: {{ remote_backup_dir | dirname }}/{{ ansible_date_date.date }}_ocla.ca_backup.tar.gz

s3_backup_bucket_name: ocla.ca_backups
