- name: restore mysql database
  mysql_db: >
    name={{ ocla_db_name }}
    state=import
    target={{ remote_backup_mysql_dump }}
    login_user={{ ocla_db_user_name }}
    login_password={{ ocla_db_user_pass }}
    login_host="localhost"

