---

- include: ../ansible-common/deploy-base-server.yml

- name: deploying site
  hosts: webservers
  roles:
    - php_requirements
    - geerlingguy.apache
    - ANXS.mysql
    - darthwade.wordpress
  tasks:
    - service: name=apache2 state=restarted
  sudo: True
