---

- name: fetch backup data from s3
  hosts: webservers
  tasks:
    - name: fetch backup data from s3
      s3: >
        aws_access_key={{ aws_access_key }}
        aws_secret_key={{ aws_secret_key }}
        bucket={{ s3_backup_bucket_name }}
        object={{ s3_backup_archive }}
        dest={{ remote_backup_dir | dirname }}/{{ s3_backup_archive | basename }}
        mode=get
    - name: create backup directory if it does not exist
      file: path={{ remote_backup_dir }} state=directory
    - name: unpack backup archive
      unarchive: >
        copy=no
        src={{ remote_backup_dir | dirname }}/{{ s3_backup_archive | basename }}
        dest={{ remote_backup_dir }}
    - name: remove backup archive
      file: >
        path={{ remote_backup_dir | dirname }}/{{ s3_backup_archive | basename }}
        state=absent

- name: restore site
  hosts: webservers
  roles:
    - mysql_restore
    - wordpress_restore
    - cleanup_backup_data

