- name: restore wp-content/ directory
  shell: /bin/cp -r {{ remote_backup_wordpress_dir }}/wp-content/* {{ apache_document_root }}/wp-content/
  sudo: True

- name: restore .htaccess file
  shell: /bin/cp {{ remote_backup_wordpress_dir }}/.htaccess {{ apache_document_root }}/.htaccess
  sudo: True

