# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

    config.vm.define "vagrant.ocla.ca" do |db|
        db.vm.box = "hashicorp/precise32"
        db.vm.network :private_network, ip: "192.168.33.11"

        # Use the vagrants-hostsupdater plugin to add this machine to the host
        # machine's /etc/hosts file
        db.vm.hostname = "vagrant.ocla.ca"

    end

    # provision with ansible
    config.vm.provision "ansible" do |ansible|
        ansible.playbook = "ansible/deploy_server.yml"
        ansible.groups = {
            "webservers" => ["vagrant.ocla.ca"]
        }
    end

end
